### ISSUE TITLE
Error: Non-base58 character

### ISSUE THREAD

**Issue by Scofield-04-21-076** [near/near-api-js#1043]
**Describe the bug**

I launch:
node script.js

I get the following error:

var/utils/node_modules/base-x/src/index.js:111
    throw new Error('Non-base' + BASE + ' character')
          ^

Error: Non-base58 character
    at Object.decode (/var/utils/node_modules/base-x/src/index.js:111:11)
    at baseDecode (/var/utils/node_modules/borsh/lib/index.js:46:39)
    at new KeyPairEd25519 (/var/utils/node_modules/near-api-js/lib/utils/key_pair.js:100:100)
    at Function.fromString (/var/utils/node_modules/near-api-js/lib/utils/key_pair.js:74:20)
    at /var/utils/script.js:30:27

script.js:30:27:
const keyPair = KeyPair.fromString(PRIVATE_KEY);

The error only appears when I run script.js on the server, but on the local laptop everything works fine.

Can anyone please help me?

**Desktop:**
 - OS: [Linux Mint ]
 - Version [20.3]

**Server:**
 - OS: [Linux Ubuntu ]
 - Version [20.04.5 LTS]

**Comment by andy-haynes** [comment]
Hi @Scofield-04-21-076, this error is indicating that there are non-base58 characters in the string passed to `KeyPair.fromString()`. Usually this means you're including the `ed25519:` prefix, which is invalid because of the `:` (only the part after the `:` should be used).

If you log the argument being passed on the server you should be able to tell whether it's bad data or just needs the prefix removed.
