### ISSUE TITLE
http could not be found within the project

### ISSUE THREAD

**Issue by Mylnikov1337Kirill** [near/near-api-js#1109]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [ ] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

After migrating from `1.1.0` to the latest `2.0.4` on our `react-native` app started to face this error 

![image](https://user-images.githubusercontent.com/26140589/231183844-0d0ea3c7-fdde-4134-8248-ac8b0d9e45c4.png)

```
Error: Unable to resolve module http from /Users/kirillmylnikov/Dev/sweat-wallet/node_modules/@near-js/providers/lib/fetch.js: http could not be found within the project or in these directories:
  node_modules/@near-js/providers/node_modules
  ```
  
My assumptions that the issue is the library used for the network purposes (actual `node-fetch`) is not isomorphic.

### Steps to reproduce

1. boot any react-native app
2. install near-api-js
3. the red screen appears while the building process

### Expected behavior

No red screens. 
In depth: I expect the library to be available across the various js environments

### Actual behavior

It crashes

### Your environment

- NEAR JavaScript API version used: 2.0.4
- Frontend framework (if applicable): react-native
- Relevant dependencies (if applicable): -

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by andy-haynes** [comment]
Hi @Mylnikov1337Kirill thank you for filing this issue!

I see the problem came from the packages refactor where this was missed. Previously the global `fetch` injection implicitly took place in a module which would have been unavailable to React Native environments but the basic `Provider` usage was unaffected. Now that `fetch` is sourced at load time, the problem has been promoted from breaking the `connect` module to breaking the entire `@near-js/providers` package 🤦 

I'll have a PR up shortly with a fix, we should be able to publish the fix this week.
