### ISSUE TITLE
setup-node-fetch breaks another libraries in the project

### ISSUE THREAD

**Issue by magmel48** [near/near-api-js#1138]
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [ ] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

this setup-node-fetch function

https://github.com/near/near-api-js/blob/299ce39b943f1692f6359f5b9250102caaa3fb85/packages/near-api-js/src/utils/setup-node-fetch.ts#L18

replaces global.fetch

https://github.com/near/near-api-js/blob/299ce39b943f1692f6359f5b9250102caaa3fb85/packages/near-api-js/src/connect.ts#L31

first, it's not OK to replace global functions and the behaviour should be avoided. Second, it breaks another libraries usage in the same project if the another libraries are using fetch with request object (https://developer.mozilla.org/en-US/docs/Web/API/Request) instead of string url

### Steps to reproduce

1. Require near-api-js in your script.
2. Use fetch with Request object instead of string url.

### Expected behavior

this script must be changed with at least checking if Request object passed. But it would be much better to avoid replacing global.fetch

### Actual behavior

TypeError: Invalid URL

### Your environment

- NEAR JavaScript API version used:
- Frontend framework (if applicable):
- Relevant dependencies (if applicable):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by magmel48** [comment]
@andy-haynes

**Comment by andy-haynes** [comment]
The injection of a global `fetch` is done in `near-api-js` for backward compatibility. It will likely remain in place up until `near-api-js` is eventually deprecated in favor of the `@near-js` packages.

Please use the `@near-js` packages directly instead of `near-api-js` to avoid injection into global scope. See https://github.com/near/near-api-js/blob/master/MIGRATION.md for a guide to migrating from `near-api-js`. Note that there is no analog for the `connect` function in the `@near-js` packages, so you would need to initialize a `Near` object directly and, if applicable, initialize the keystores according to the logic in `connect`.

**Comment by magmel48** [comment]
ok, thank you, update our solution. BTW, you don't expose `utils.serialize.base_decode/encode`, but it seems is exposed as-is from `borsh` library.
