### ISSUE TITLE
Create transactions and redirect to /sign in the NEAR Wallet without logging in first

### ISSUE THREAD

**Issue by kcole16** [near/near-api-js#448]
***Problem***
 Currently, apps must always have their users "login" via the NEAR Wallet by adding an access key, before they can sign any transaction that includes a NEAR deposit. This is because the entire transaction is serialized before redirecting to the wallet, and the account name must be known ahead of time so it can be included. 

***Solution***
 Allow devs to send an unserialized TX to the wallet (or serialized without the account name and recovered in the wallet), so they do not need to implement "login" just to get the account name.

**Comment by kcole16** [comment]
Linked Wallet issue: https://github.com/near/near-wallet/issues/1148

**Comment by mikedotexe** [comment]
Is this still the case? I believe I've seen the behavior working, or what I'm interpreting this behavior to be. Maybe this is slightly different than what I'm picturing in my head.
Before, if a user was redirected to Wallet and didn't have an account, they'd have to sign up, then essentially follow the link again in order to confirm a transaction. It seems like that was fixed and pretty adjacent to what we're discussing here.

**Comment by vikinatora** [comment]
Hey everyone, I'm currently conducting a clean-up on the issues of NAJ. Please let me know if this isuse is still relevant; otherwise, I'll proceed to close the issue in 5 days.
