### ISSUE TITLE
getAccountDetails returns empty transactions array

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#525]
**Describe the bug**
`getAccountDetails` function claims to return transactions but always returns nothing.
See https://github.com/near/near-api-js/blob/960b798fe009fe0658637803af9645f550f139cb/src/account.ts#L402

**To Reproduce**
1. Create `let account = new Account(account_id);`
2. Call `account.getAccountDetails()`
3. Observe the empty `transactions` in the result

**Expected behavior**
Should remove this field and update comments as it's confusing

**Comment by frol** [comment]
@ilblackdragon Ironically, it was your commit introducing this empty list: https://github.com/near/near-api-js/commit/13a0271befb44b6251943388dc49ab0a433fd1f2 :smile:

**Comment by mehtaphysical** [comment]
What do you think about:

1. Making the query a generic function `query<T>(...): https://github.com/near/near-api-js/blob/master/src/providers/provider.ts#L251
2. adding types for each query request_type `view_account`, `view_code`, `view_state`, `view_access_key`, `view_access_key_list`, `call_function`
3. so that `getAccessKeys` returns an `AccessKeyInfo`: https://github.com/near/nearcore/blob/master/core/primitives/src/views.rs#L233
4. and then create a type for `getAccountDetails` without the transactions

I know that's a lot of changes for this small thing, but it will improve the typing throughout the application and thus improve the documentation.

If that sounds good I'll make a PR.

**Comment by frol** [comment]
@mehtaphysical I am all for the strict typing. I am not sure I grasped your idea, though. There is already a generic 'query' method (btw, see the docs for the latest 'query' API: https://docs.near.org/docs/develop/front-end/rpc#view-account, we prefer object as the parameter to the 'query' rather than a stringy "path", which is soft-deprecated now)

**Comment by mehtaphysical** [comment]
Oh i mean typescript generic. So instead of https://github.com/near/near-api-js/blob/master/src/providers/json-rpc-provider.ts#L92 it would look like:

```ts
async query<T>(...args: any[]): Promise<T> {
...
}
```

And there would be response types for each of the query request types like:

```ts
interface ContractState {
  key: string;
  value: string;
  proof: string;
}

interface ViewStateResult {
  values: ContractState[];
}
```

**Comment by frol** [comment]
Ah, sure! It was a collision in the terminology :smile: 

I am all for it. Please, go ahead with a PR, I will be happy to review and merge it!
