### ISSUE TITLE
WalletConnection initialisation race condition 

### ISSUE THREAD

**Issue by meta-head** [near/near-api-js#857]
**Describe the bug** async method `WalletConnection._completeSignInWithAccessKey` called from constructor cause `keyStore.getKey` to fail to fetch the key

**To Reproduce** after wallet login and return back to `?account_id=test.testnet&public_key=ed25519%..` in the code

const keyStore = new nearApi.keyStores.BrowserLocalStorageKeyStore(); const near = await nearApi.connect(

 {keyStore, ...nearConfig} 

); const walletConnection = new nearApi.WalletConnection(near); const keyPair = await keyStore.getKey(nearConfig.networkId, walletConnection.getAccountId())

keyPair is null

**Expected behavior** keyPair should have a valid key

**Additional context** looks like the reason is: async method `WalletConnection._completeSignInWithAccessKey` called from constructor [https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L93](https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L93) might not finish before `keyStore.getKey` tries to fetch the key

**Comment by amirsaran3** [comment]
We have the pending key in `localStorage` after we redirect back from the Near Wallet. While the key is being moved from pending to permanent storage (with `_moveKeyFromTempToPermanent`) we are trying to access the permanent version. That's why it's `null`.

I added a optional `checkForPendingKey = false` parameter to check for pending key as a fallback option if it can't find the permanent one. 

With this method your code will work.
![image](https://user-images.githubusercontent.com/95852708/176693092-f21e3275-dba1-4bf0-aea8-27ce925e2b53.png)

**Comment by zcstarr** [comment]
+1 to this issue.
