### ISSUE TITLE
Access to fetch at 'https://rpc.testnet.near.org/' from origin 'http://localhost:3000' has been blocked by CORS policy

### ISSUE THREAD

**Issue by masafumimori** [near/near-api-js#892]
**Describe the bug** When I try to call method with connecting to testnet from `localhost:3000`, the CORS error occurs.

Access to fetch at '[https://rpc.testnet.near.org/](https://rpc.testnet.near.org/)' from origin '[http://localhost:3000](http://localhost:3000)' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Do I need to run the node locally using Docker to test interaction with smart contracts?

**To Reproduce** Steps to reproduce the behavior:

1.  Go to '[my repo](https://github.com/masafumimori/dApps_samples)'
2.  Clone the project
3.  Move to `near-wasm` directory
4.  yarn install & yarn dev
5.  Go to `[http://localhost:3000](http://localhost:3000)([http://localhost:3000)([http://localhost:3000)([http://localhost:3000](http://localhost:3000](http://localhost:3000)([http://localhost:3000](http://localhost:3000](http://localhost:3000)([http://localhost:3000)([http://localhost:3000](http://localhost:3000](http://localhost:3000)([http://localhost:3000](http://localhost:3000))))`
6.  click `Login` button displayed and press `+` button

**Expected behavior** Can call method on testnet.

**Desktop (please complete the following information):**

*   OS: MacOS M1Pro
*   Version Monetary v12.0

**Comment by masafumimori** [comment]
I created local dev environment following [this](https://docs.near.org/docs/tools/kurtosis-localnet).
But I still get the same CORS policy issue.

```
Access to fetch at 'http://127.0.0.1:8332/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

So, might be because of `Vite.js` I am using, instead of `near-api-js`.

**Comment by morgsmccauley** [comment]
@masafumimori The reason you are getting CORS errors is because you are adding a [non-supported header](https://github.com/masafumimori/dApps_samples/blob/master/near-wasm/frontend/src/components/Near/config.ts#L44) to the requests sent to the RPC endpoint. The browser will block any requests which contain headers which are not present in the [access-control-allowed-headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) response header.

`headers` is currently required in the `connect` configuration, but you can set it to an empty object to work around this.

**Comment by marcinbodnar** [comment]
Thank you @morgsmccauley 
Closing the issue.
