### ISSUE TITLE
env file not exists

### ISSUE THREAD

**Issue by A2DNEW** [near/near-api-js#924]
I use this code for create new account:

`createAccount(process.argv<span class="error"><span class="error"><span class="error">[2]</span></span></span>, process.argv<span class="error"><span class="error"><span class="error">[3]</span></span></span>, process.argv<span class="error"><span class="error"><span class="error">[4]</span></span></span>);`

But I don't find any ENV file in repository.

How can I replace `process.argv` with my variable?

For exapmle, Where can I create `creatorAccountId` for my self?

**Comment by morgsmccauley** [comment]
[process.argv](https://nodejs.org/docs/latest/api/process.html#processargv) represents arguments passed via the command line rather than environment variables.

Assuming you're referring to this [file](https://github.com/near/near-api-js/blob/master/examples/cookbook/accounts/create-testnet-account.js), this must be run via the command line like so:
```sh
node create-testnet-account.js CREATOR_ACCOUNT NEW_ACCOUNT AMOUNT
```
Where:
* `CREATOR_ACCOUNT` is the account which initiates the creation
* `NEW_ACCOUNT` is the account to be created
* `AMOUNT` is the amount of NEAR which will be fed to the new account from the creator account

To successfully create a new account, the creator accounts access keys must be available to the above command. You'll need to [log in to the CLI](https://docs.near.org/tools/near-cli#near-login) to achieve this.
